spring:
  application:
    name: "refrigerator"

  datasource:
    url: jdbc:h2:file:./db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    show-sql: true

  sql:
    init:
      mode: embedded

  threads:
    virtual:
      enabled: true